runtime: python38 # or another supported version

instance_class: F1 # this is the cheapest option

env_variables:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "********"
  MYSQL_DB: "db_course_explorer"
  MYSQL_HOST: 34.71.95.147

handlers:

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles